### ISSUE TITLE
Spotify Wrapper Listing

### ISSUE THREAD

**Issue by hughrawlinson** [blmstrm/clj-spotify#8]
Hi!

Thanks so much for developing this wrapper for the Spotify Web API for Clojure. I've just tried it out, it's working really well. I work for Spotify, and I'm wondering if you'd be interested in having this project listed on our [developer site](https://developer.spotify.com/web-api/code-examples/), alongside other Spotify Web API wrappers in other languages?

Best,

Hugh

**Comment by blmstrm** [comment]
Hello!

Yeah, that would be great! Thanks for taking your time trying the wrapper out and I am glad you liked it!

Kind regards,

Kalle

**Comment by hughrawlinson** [comment]
[Done!](https://developer.spotify.com/web-api/code-examples/)

**Comment by blmstrm** [comment]
Hi again,

I checked out the code example page but it seems like the hyperlink back to here is missing, I mean the text is there but it doesn't link anywhere.

Kind regards,

Kalle

**Comment by hughrawlinson** [comment]
Hey Kalle, just fixed it 😄
